### ISSUE TITLE
complie error after upgrade ffmpeg from 4.4.1 to 5.0 

### ISSUE THREAD

**Issue by sirlaurie** [clangen/musikcube#497]
macbook pro 16, M1 Max
macOS 12.2

below is error message:

[ 32%] Linking CXX shared library ../../../bin/plugins/libhttpdatastream.dylib
[ 32%] Built target httpdatastream
[ 33%] Building CXX object src/plugins/stockencoders/CMakeFiles/stockencoders.dir/main.cpp.o
[ 33%] Building CXX object src/plugins/stockencoders/CMakeFiles/stockencoders.dir/LameEncoder.cpp.o
[ 33%] Building CXX object src/plugins/stockencoders/CMakeFiles/stockencoders.dir/FfmpegEncoder.cpp.o
~/Downloads/musikcube/src/plugins/stockencoders/FfmpegEncoder.cpp:255:25: error: assigning to 'AVCodec *' from 'const AVCodec *' discards qualifiers
    this->outputCodec = avcodec_find_encoder(it->second);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~/Downloads/musikcube/src/plugins/stockencoders/FfmpegEncoder.cpp:365:5: error: use of undeclared identifier 'av_register_all'
    av_register_all();
    ^
2 errors generated.
make[2]: *** [src/plugins/stockencoders/CMakeFiles/stockencoders.dir/FfmpegEncoder.cpp.o] Error 1
make[1]: *** [src/plugins/stockencoders/CMakeFiles/stockencoders.dir/all] Error 2
make: *** [all] Error 2

**Comment by clangen** [comment]
Thanks for the heads up here -- I've fixed the build issues in the `master` branch and will see about getting a release out soon.

**Comment by sirlaurie** [comment]
> Thanks for the heads up here -- I've fixed the build issues in the `master` branch and will see about getting a release out soon.

complie succeed on on my intel macbook pro. I'll test on M1 later.

**Comment by sirlaurie** [comment]
works on M1 too!

**Comment by edsu** [comment]
Thanks for the quick attention on this! I'm kind of new to homebrew. I think I'm still seeing the same error when doing a `brew install musikcube`? I've attached the build log here in case it is useful:

[02.make](https://github.com/clangen/musikcube/files/8022899/02.make.txt)

**Comment by sirlaurie** [comment]
> Thanks for the quick attention on this! I'm kind of new to homebrew. I think I'm still seeing the same error when doing a `brew install musikcube`? I've attached the build log here in case it is useful:
> 
> [02.make](https://github.com/clangen/musikcube/files/8022899/02.make.txt)

author hasn't update brew tap source, so brew still use old version to install.

just wait for author

**Comment by clangen** [comment]
Sorry for the delay, this breakage came at a bad time as I was in the middle of re-writing the build system. The work has been completed, and a new version has been published to homebrew.

Please let me know if you have additional issues! Closing for nowo.

**Comment by edsu** [comment]
`brew install` works now -- thanks for helping me get my fav music player back!
