### ISSUE TITLE
Fails to build with FFmpeg 8.0

### ISSUE THREAD

**Issue by yurivict** [clangen/musikcube#736]
[log](https://bz-attachments.freebsd.org/attachment.cgi?id=263163)

**Comment by mandree** [comment]
To make that useful, I've pulled the errors from Yuri's log for an initial glance:

```
/wrkdirs/usr/ports/multimedia/musikcube/work/musikcube-3.0.4/src/plugins/ffmpegdecoder/FfmpegDecoder.cpp:270:13: error: use of undeclared identifier 'avcodec_close'; did you mean 'avio_close'?
  270 |             avcodec_close(this->codecContext);
      |             ^~~~~~~~~~~~~
      |             avio_close
/usr/local/include/libavformat/avio.h:693:5: note: 'avio_close' declared here
  693 | int avio_close(AVIOContext *s);
      |     ^
/wrkdirs/usr/ports/multimedia/musikcube/work/musikcube-3.0.4/src/plugins/ffmpegdecoder/FfmpegDecoder.cpp:270:27: error: cannot initialize a parameter of type 'AVIOContext *' with an lvalue of type 'AVCodecContext *'
  270 |             avcodec_close(this->codecContext);
      |                           ^~~~~~~~~~~~~~~~~~
/usr/local/include/libavformat/avio.h:693:29: note: passing argument to parameter 's' here
  693 | int avio_close(AVIOContext *s);
      |                             ^
2 errors generated.
```

I think the compiler is off though and the solution might be replacing avcodec_close by avcodec_free_context (but that might change semantics!) -> https://ffmpeg.org/doxygen/7.0/group__lavc__core.html#gab7f632082a10fcb051fa3e2db7f86942

**Comment by clangen** [comment]
Hey, thank you both for the report. The past year or so I've been struggling to find time to maintain the app, but fortunately it hasn't seen much breakage. The FFMPEG8 update changed that.

I've pushed some changes to the `master` branch recently that should address the build errors. I've also been set back due to some hardware failures, but just this weekend I managed to get a FreeBSD installation up and working again, and the app is compiling and running with the 14.3 release.

Other dependencies had to be updated along the way for other platforms to get it to build cleanly for all supported environments. I'm planning to do a release soon, just as soon as I can do some more extensive testing.

**Comment by clangen** [comment]
A new version has been released that should address this issue.
